import axios from 'axios';

// --- Configuration ---
const API_BASE = 'https://api.mail.tm';
const TIMEOUT = 15000;

// --- Helpers ---

async function fetchMessages(token) {
  try {
    const { data } = await axios.get(`${API_BASE}/messages`, {
      headers: { Authorization: `Bearer ${token}` },
      timeout: TIMEOUT
    });
    return data['hydra:member'] || [];
  } catch (err) {
    if (err.response?.status === 401) throw new Error('Invalid or expired token.');
    throw new Error(err.message);
  }
}

/**
 * Inbox Checker Command
 * Checks messages for a Mail.tm account using a token.
 */
export const meta = {
  name: 'inbox',
  version: '1.1.0',
  aliases: ['checkmail', 'readmail'],
  description: 'Check temporary email inbox.',
  author: 'AjiroDesu',
  prefix: 'both',
  category: 'tools',
  type: 'anyone',
  cooldown: 5,
  guide: ['<token>']
};

export async function onStart({ args, response, usage }) {
  const token = args[0];

  if (!token) {
    return response.reply(
      `⚠️ **Missing Token**\n` +
      `Please provide the token generated by \`/tempmail\`.\n\n` +
      `Usage: \`/inbox <token>\``
    );
  }

  const loading = await response.reply('📬 **Fetching inbox...**');

  try {
    const messages = await fetchMessages(token);

    if (messages.length === 0) {
      return response.edit('text', loading, '📭 **Inbox is empty.**');
    }

    const formatted = messages.map((m, i) => {
      const from = m.from?.address || 'Unknown';
      const subject = m.subject || 'No Subject';
      const date = new Date(m.createdAt).toLocaleString();
      const status = m.seen ? 'Read' : 'Unread';

      return `✉️ **${i + 1}.** ${subject}\n` +
             `   From: \`${from}\`\n` +
             `   Date: ${date} | Status: ${status}`;
    }).join('\n\n');

    await response.edit('text', loading, `📥 **Inbox Messages**\n\n${formatted}`);

  } catch (err) {
    await response.edit('text', loading, `⚠️ **Error:** ${err.message}`);
  }
}